### ISSUE TITLE
color does not get set when light has been off; restore previous state on toggle

### ISSUE THREAD

**Issue by gretel** [Danimal4326/homebridge-hyperion#14]
basically things work fine, thanks.
i have to ask siri twice to set one color if the light has been off. on the *second* time the color gets set correctly.
just asking to switch the light on results in the color not matching the previous state - it's always white.

**Comment by pattyland** [comment]
Is it working just to change the color when the lights are on? I'm still trying to find a pattern here... I looks like using siri to change the colors is working randomly... Using the Home App it's working great

**Comment by gretel** [comment]
the lights have to be on for the color to be set. how would you change the color when the light is off? 🐒

**Comment by Danimal4326** [comment]
From what I remember, tt depends on what app you use to control the lights.  Some controllers send an explicit "on" command with every color change, others only send a color change command.  

I got a new tv so I have not set up lightpack/hyperion yet.  I currently have no way to test things out.

**Comment by SSSTREDDD** [comment]
I have the same issue but only when setting scenes that include a brightness change and new color. This happens when using siri or the control center widget to set the scene. the brightness will change properly but the color will revert to white. Strangely the issue does not happen when using the "test scene" option in the home app and also works properly when setting the color directly. Something about the behavior of scene handling is off it seems.

**Comment by gretel** [comment]
@SSSTREDDD actually i did only use siri.. so that makes sense to me.
